[package]
name = "dynamixel2"
version = "0.1.0"
license = "BSD-2-Clause"
authors = [
	"Maarten de Vries <maarten@de-vri.es>",
	"RoboHouse <robohouse@robovalley.com>",
]

readme = "README.md"

edition = "2018"

[dependencies]
log = { version = "0.4.8", optional = true }

[dev-dependencies]
assert2 = "0.2.1"
env_logger = "0.7.1"
serial = "0.4.0"
