[package]
name = "dynamixel2"
version = "0.2.3"
license = "BSD-2-Clause"
authors = [
	"Maarten de Vries <maarten@de-vri.es>",
	"RoboHouse <robohouse@robovalley.com>",
]

description = "dynamixel protocol 2.0"
keywords = ["dynamixel", "servo", "motor", "serial"]
categories = ["science::robotics"]
repository = "https://github.com/robohouse-delft/dynamixel2-rs"
readme = "README.md"

edition = "2018"

[dependencies]
log = { version = "0.4.8", optional = true }

[dev-dependencies]
assert2 = "0.3.3"
env_logger = "0.9.0"
serial = "0.4.0"

[workspace]
members = ["dynamixel2-cli"]
