[package]
name = "dynamixel2-cli"
version = "0.1.0"
edition = "2018"

[dependencies]
dynamixel2 = { version = "0.1.4", path = "..", features = ["log"] }
env_logger = "0.8.3"
log = "0.4.14"
serial = "0.4.0"
structopt = "0.3.21"
